### ISSUE TITLE
해봤는데....

### ISSUE THREAD

**Issue by opqriu** [kwstephenkim/hwpviewer#1]
https://www.imageupload.net/image/KzUft

안 돼요 ^^;
Debian 10 환경이구요.
난감하시면 그냥 답변 안 달아 주셔도 괜찮습니다.
감사합니다.

**Comment by opqriu** [comment]
아. sudo를 안 넣었군요 -_-
add
그래도 안 되요.
음, 웹 오피스를 쓰겠습니다 3_3

**Comment by opqriu** [comment]
[sudo] 암호: 
./gen-dockerfile.sh 
cp: cannot stat './Dockerfile.template': 그런 파일이나 디렉터리가 없습니다
+ docker build --build-arg __USER__=root --build-arg __GROUP__=root --build-arg __UID__=0 --build-arg __GID__=0 --build-arg __TIMEZONE__=Asia/Seoul -t myhwpviewer:1.0 -f Dockerfile /home/user/hwpviewer
Sending build context to Docker daemon  75.08MB
Step 1/26 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
f08d8e2a3ba1: Pull complete 
3baa9cb2483b: Pull complete 
94e5ff4c0b15: Pull complete 
1860925334f9: Pull complete 
Digest: sha256:05a58ded9a2c792598e8f4aa8ffe300318eac6f294bf4f49a7abae7544918592
Status: Downloaded newer image for ubuntu:18.04
 ---> 6526a1858e5d

이후에 엄청 오래 뭔가를 설치 해구요.
이렇게 끝났습니다.

Step 18/26 : COPY ${__HANCOM__} .
 ---> ce4248654b2c
Step 19/26 : RUN dpkg -i ${__HANCOM__} && rm -f ${__HANCOM__}
 ---> Running in edbb13b3bf48
Selecting previously unselected package hancomoffice-hwpviewer.
(Reading database ... 54921 files and directories currently installed.)
Preparing to unpack hancomoffice-hwpviewer-Ubuntu-amd64.deb ...
Unpacking hancomoffice-hwpviewer (9.20.0.1573) ...
Setting up hancomoffice-hwpviewer (9.20.0.1573) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Removing intermediate container edbb13b3bf48
 ---> 997d0ed12706
Step 20/26 : RUN echo "root:sophia_corynn" | chpasswd
 ---> Running in 4c3786362983
Removing intermediate container 4c3786362983
 ---> 3de7728454ce
Step 21/26 : RUN groupadd -g ${__GID__} ${__GROUP__} || true
 ---> Running in 31325e65993f
groupadd: group 'root' already exists
Removing intermediate container 31325e65993f
 ---> f9761aeb3543
Step 22/26 : RUN useradd -m     -G sudo -s /bin/bash -g ${__GID__} -u ${__UID__} ${__USER__}
 ---> Running in ab9b383e7c14
useradd: user 'root' already exists
The command '/bin/sh -c useradd -m     -G sudo -s /bin/bash -g ${__GID__} -u ${__UID__} ${__USER__}' returned a non-zero code: 9
make: *** [Makefile:9: build] 오류 9

user@guserz:~/hwpviewer$ sudo make run

./run-my-docker.sh "myhwpviewer:1.0" -v$HOME:/$HOME/"host"
+ docker run --rm -e DISPLAY=:0 -e HOST_UID=0 -e HOST_GID=0 -e HOST_USER=root -e HOST_GROUP=root -v /tmp/.X11-unix:/tmp/.X11-unix -v /root/.ssh:/root/.ssh -v/root://root/host -it myhwpviewer:1.0
Unable to find image 'myhwpviewer:1.0' locally
docker: Error response from daemon: pull access denied for myhwpviewer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make: *** [Makefile:12: run] 오류 125

**Comment by kwstephenkim** [comment]
코멘트를 이제 봤네요. 여긴 시간이 좀 늦어서 내일 짬 내서 확인해 보겠습니다.

**Comment by kwstephenkim** [comment]
아. 에러 메시지를 읽어보니 root로 스크립트를 실행하신 것 같은데, 일반 유저로 하셔야 해요.

**Comment by kwstephenkim** [comment]
그리고 제가 파일을 잘못 올린 게 맞네요. 확인해 보고 새로 커밋하겠습니다.

**Comment by kwstephenkim** [comment]
Hello, 

I have taken a look at it. I guess all that are needed is:
 1. Renaming Dockerfile to Dockerfile.template
 2. Run make && make run not as root but as a regular user

Please let me know if the issue is reproducible. Thank you!

**Comment by kwstephenkim** [comment]
Besides, if Dockerfile is renamed to Dockerfile.template, Makefile should be modified accordingly.

**Comment by kwstephenkim** [comment]
> https://www.imageupload.net/image/KzUft
> 
> 안 돼요 ^^;
> Debian 10 환경이구요.
> 난감하시면 그냥 답변 안 달아 주셔도 괜찮습니다.
> 감사합니다.

I believe this error occurs because your account was not added to docker group. Please try this: 
 sudo gpasswd -a $USER docker

Following that, please re-login. 

Without those, I would assume that "docker run hello-world" should've failed. The command should succeed to run my docker container.
